sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bhandarihardik/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true bhandarihardik/docker-react-app npm run test
  
deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'Docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-948077300943'
  bucket_path: 'Docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
